version: '3.8'

services:
  ipatool:
    image: heard/ipatool
    container_name: ipatool
    ports:
      - "8080:8080"
    volumes:
      - ipa-data:/app/data
      - ipa-downloads:/app/downloads
    restart: unless-stopped

volumes:
  ipa-data:
  ipa-downloads:
